### ISSUE TITLE
Not found resource. 

### ISSUE THREAD

**Issue by pblaravel** [statikbe/laravel-nova-chained-translation-manager#24] opened 2022-11-27 13:29 UTC
<img width="2047" alt="image" src="https://user-images.githubusercontent.com/10829306/204137882-7f80974e-3f87-4e97-80f1-e2f5aa582f4e.png">

**Comment by pblaravel** [comment] 2022-11-27 13:29
please help resolve this problem

**Comment by sten** [comment] 2022-11-28 09:00
@pblaravel Can you provide us with more information?
From the screenshot, it looks like Laravel is not loading Nova. Can you check if /administrator works?

**Comment by pblaravel** [comment] 2022-11-28 16:50
https://user-images.githubusercontent.com/10829306/204335150-b99d2a40-896f-49b0-8ccd-91d1e00ffc72.mov

**Comment by stijnelskens** [comment] 2022-11-30 11:19
@pblaravel I did a clean install on new project and it works just fine here!

Can you provide your version of:
- Nova
- Laravel-nova-chained-translation-manager

Did you follow the right steps listed in the readme?

**Comment by pblaravel** [comment] 2022-12-03 09:59
Nova : 4.19.3
Laravel-nova-chained-translation-manager: 3.0.4

**Comment by pblaravel** [comment] 2022-12-03 10:01
Yes execute all steps from readme

**Comment by sten** [comment] 2022-12-07 15:06
@pblaravel It is very hard to help you without seeing the code. We cannot replicate your situation.
Can you please provide the code in a git repo?

**Comment by sten** [comment] 2023-02-16 10:16
I will close this, since it is not reproducable and no feedback is provided.

**Closed by sten** 2023-02-16 10:16 UTC
