### ISSUE TITLE
CSS brakes nova layout

### ISSUE THREAD

**Issue by 7ammer** [statikbe/laravel-nova-chained-translation-manager#19] opened 2022-10-31 19:05 UTC
The css included in v3.0.1 appears to be braking the nova layout on other resources.

<img width="1160" alt="Screenshot 2022-10-31 at 19 03 56" src="https://user-images.githubusercontent.com/3194029/199089803-b8f94cdf-8ee9-479c-913c-a273c2a14c48.png">

**Comment by stijnelskens** [comment] 2022-11-09 13:17
@7ammer
Does it brake on multiple pages? Is the translation page also broken?

**Comment by alexstewartja** [comment] 2022-11-15 11:26
@stijnelskens  
Looking across the CSS file, I'm seeing where you're overriding global CSS rules that are already in Tailwind.

I recommend writing custom CSS classes and attaching them to your elements on the translations page, keeping them from applying globally to all Nova elements.

Alternatively, everything that you've written in the CSS is achievable with Tailwind utility classes. Take a look at the docs: https://tailwindcss.com/docs/

**Comment by alexstewartja** [comment] 2022-11-15 12:50
@7ammer
Until #21 is merged, you can use my branch, which fixes the visual issues

**Comment by stijnelskens** [comment] 2022-11-16 10:36
@alexstewartja Thx for your reply!
Unfortunately I cannot reproduce this issue! I'll try another deep dive into this!

**Comment by alexstewartja** [comment] 2022-11-16 13:38
> @alexstewartja Thx for your reply! Unfortunately I cannot reproduce this issue! I'll try another deep dive into this!

To be honest, this package deviates far away from what nova sets as standard for 3rd-party tools. If you're going to override core Tailwind classes, do it in a way that doesn't affect core utility classes.

That's the point of this PR

**Comment by Kobo-one** [comment] 2022-11-22 10:03
This has been fixed in the latest release ([v3.0.3](https://packagist.org/packages/statikbe/laravel-nova-chained-translation-manager#v3.0.3)).

Thanks to @alexstewartja.

**Closed by Kobo-one** 2022-11-22 10:03 UTC
Labels: bug
